name: Staging Deployment

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Mimoto To Staging
    uses: ./.github/workflows/deploy-eks.yml
    with:
      aws_region: ${{ vars.AWS_REGION }}
      aws_role_to_assume: ${{ vars.STAGING_GITHUB_ACTIONS_AWS_ROLE_ARN }}
      eks_cluster_name: ${{ vars.STAGING_EKS_CLUSTER_NAME }}
      kubernetes_namespace: ${{ vars.STAGING_KUBERNETES_NAMESPACE }}
      helm_release_name: mimoto
      helm_chart_path: deployment-configs/helm/mimoto-helm/helm/mimoto
      deployment_configs_ref: main
    secrets:
      deployment_configs_token: ${{ secrets.DEPLOYMENT_CONFIGS_TOKEN }}
      discord_webhook: ${{ secrets.DISCORD_STAGING_BUILDS_URL }}